# Chart.yaml
apiVersion: v2
name: parliament
description: A Helm chart for Parliament AI Swarm Framework
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: rabbitmq
    version: 11.x.x
    repository: https://charts.bitnami.com/bitnami