# values.yaml
replicaCount: 1
image:
  repository: nolanpriebe/parliament
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80

rabbitmq:
  auth:
    username: npriebe
    existingPasswordSecret: rabbitmq-admin-password
    existingErlangSecret: rabbitmq-erlang-cookie
  metrics:
    enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hostname: rabbitmq.192.168.40.230.nip.io
    path: /
    pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: traefik

