name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Update versions
      run: |
        # Generate a version based on timestamp
        VERSION=$(date +%Y.%m.%d-%H%M%S)
        
        # Update Chart.yaml
        sed -i "s/version: .*/version: $VERSION/" parliament/Chart.yaml
        sed -i "s/appVersion: .*/appVersion: \"$VERSION\"/" parliament/Chart.yaml
        
        # Update values.yaml
        sed -i "s/tag: .*/tag: $VERSION/" parliament/values.yaml
        
        # Commit and push if there are changes
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add parliament/Chart.yaml parliament/values.yaml
        git commit -m "Update versions to $VERSION" || echo "No changes to commit"
        git push
        
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/parliament:latest

    - name: Update deployment file
      run: |
        sed -i 's|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/parliament:latest|' deploy/deployment.yaml
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add deploy/deployment.yaml
        git commit -m "Update image tag" || echo "No changes to commit"
        git push
