name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

    - name: Update Helm chart
      run: |
        sed -i 's|tag:.*|tag: ${{ github.sha }}|' parliament/values.yaml

    - name: Setup Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.4.0

    - name: Generate Secrets
      run: |
        chmod +x ./generate-secrets.sh
        ./generate-secrets.sh

    - name: Deploy to K3s
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm dependency update ./parliament
        helm upgrade --install parliament ./parliament

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git commit -am "Update image tag" || echo "No changes to commit"
        git push